_BASE_: ../../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  MASK_FORMER:
    DEC_LAYERS: 2
    OUTLIER_SUPERVISION: True
    OUTLIER_LOSS_TARGET: "nls"
    SCORE_NORM: tanh
    OUTLIER_LOSS_FUNC: squared_hinge
  SEM_SEG_HEAD:
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res5"]
  WEIGHTS: "pretrained/swin_base_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  FREEZE_PIXEL_DECODER: True 
  FREEZE_BACKBONE: True
  FREEZE_TRANSFORMER_DECODER_EXCEPT_MLP: True
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic_coco_mix"
SOLVER:
  MAX_ITER: 5000